name: lecture-datascience
channels:
  - default
dependencies:
  - python=3.9
  - anaconda=2022.05
  - pip
  - pip:
    - joblib
    - interpolation
    - fiona
    - geopandas
    - pyLDAvis >= 3.3.0
    - gensim
    - folium
    - descartes
    - pyarrow
    - xgboost
    - graphviz
    - networkx
    - scikit-learn >= 1.0
    - bokeh
    - nltk
    - beautifulsoup4
    - seaborn
    - patsy
    - quandl
    - statsmodels
    - quantecon
    - openpyxl
    - pandas-datareader
    - plotly
    - lxml
    - nasdaq-data-link
  - conda:
    - python-graphviz
