name: lecture-datascience
channels:
  - default
dependencies:
  - python=3.8
  - anaconda
  - pip
  - pip:
    - joblib
    - interpolation
    - fiona
    - geopandas
    - pyLDAvis >= 3.3.0
    - gensim
    - folium
    - descartes
    - pyarrow
    - xgboost
    - graphviz
    - scikit-learn >= 0.24.0
    - bokeh
    - nltk
    - beautifulsoup4
    - seaborn
    - patsy
    - quandl
    - statsmodels
    - quantecon
    - openpyxl
  - conda:
    - python-graphviz
