name: lecture-datascience
channels:
  - default
dependencies:
  - python=3.8
  - anaconda=2021.05
  - pip
  - pip:
    - jupyter-book>=0.12.1,<0.13
    - sphinxext-rediraffe
    - sphinx-multitoc-numbering
    - sphinx-exercise
    - joblib
    - interpolation
    - sphinx-tojupyter
    - fiona 
    - geopandas 
    - pyLDAvis >= 3.3.0
    - gensim 
    - folium 
    - descartes 
    - pyarrow
    - xgboost
    - graphviz
    - bokeh
    - sphinxcontrib-bibtex
    - quantecon-book-theme>=0.3.0,<0.4.0
    - nltk
    - seaborn
    - patsy
    - quandl
    - statsmodels
    - quantecon
    - openpyxl
    - pandas_datareader
    - plotly
    - lxml
    - scikit-learn>1.0
    - numba
  - conda:
    - python-graphviz
