name: lecture-datascience
channels:
  - default
dependencies:
  - python=3.8
  - anaconda=2020.11
  - pip
  - pip:
    - jupyter-book==0.10.2
    - sphinxext-rediraffe
    - sphinx-multitoc-numbering
    - sphinx-exercise
    - joblib
    - interpolation
    - sphinx-tojupyter
    - qeds 
    - fiona 
    - geopandas 
    - pyLDAvis >= 3.3.0
    - gensim 
    - folium 
    - descartes 
    - pyarrow
    - xgboost
    - graphviz
    - scikit-learn >= 0.24.0
    - bokeh
    - sphinxcontrib-bibtex
    - git+https://github.com/QuantEcon/quantecon-book-theme@jupyterlab
    - nltk
  - conda:
    - python-graphviz
