# for notebooks repos only.
name: lecture-datascience-binder
channels:
  - default
dependencies:
  - python=3.8
  - anaconda=2020.07
  - pip
  - pip:
    - joblib
    - interpolation
    - qeds 
    - fiona 
    - geopandas 
    - pyLDAvis >= 3.3.0
    - git+https://github.com/QuantEcon/quantecon-book-theme
    - gensim 
    - folium 
    - descartes 
    - pyarrow
    - xgboost
    - graphviz
    - scikit-learn >= 0.24.0
    - bokeh
    - nltk
  - conda:
    - python-graphviz
